### ISSUE TITLE
Support Libgdx Android

### ISSUE THREAD

**Issue by SrJohnathan** [effekseer/EffekseerForMultiLanguages#10]
Some possibility to run on Android with libgdx ?

**Comment by durswd** [comment]
It seem that it can run by writing script to compile it.
But I don't have an enough time.
PR is welcome.

**Comment by SrJohnathan** [comment]
my English is not very good

Compile the java project for Android, with all the modifications
opengl3 to opengl es 2
but does not render

implement a surfaceView or native window?

**Comment by peed** [comment]
Compiling the code only works for Desktop right now, so it won't work as-is
on Android until a custom script is made to handle android rendering.

I'd suggest compiling it for desktop first and seeing how it works, then
adapting to android.

**Comment by durswd** [comment]
It seem that it doesn't need a surfaceView or native window.
Would you send a PR about compiling with Android?

**Comment by peed** [comment]
Unfortunately I don't have the time right now. My main focus is getting it
to work with the Desktop so I haven't even looked into anything android
related yet.

When I have time, I'll try to set up a simple compilation script for
android, but I can't make any promises.

This is pretty much the first attempt to get Effekseer working with libgdx,
so it's still early in development.
Feel free to spread the word to other libgdx developers about this as we
definitely need more people working on this.

It will be an amazing asset for libgdx/Android game development!
Thanks.

**Comment by durswd** [comment]
I sent a message to @SrJohnathan 
It is worth to compile on Android even if it doesn't run.
It makes easy to try to run on android.

**Comment by SrJohnathan** [comment]
I'm implementing on Android ...

Desktop, I implemented new features

as soon as possible, I'll put the script on my github

my game yugioh fan:
https://www.youtube.com/watch?v=tecZwDPnFXE

I will put Effekseer in this game

**Comment by durswd** [comment]
I look forward to your script.
It seem that Effekseer for libGDX on Android can run on Android because EffekseerForUnity and Cocos2d-x have already run on Android.

It's a good game!

**Comment by peed** [comment]
That's fantastic!! I'm looking forward to that and the game looks
fantastic!!

**Comment by SrJohnathan** [comment]
> I look forward to your script.
> It seem that Effekseer for libGDX on Android can run on Android because EffekseerForUnity and Cocos2d-x have already run on Android.
> 
> It's a good game!

Yes, I'm using this Unity project as an example to implement on android

**Comment by SrJohnathan** [comment]
can help me, the compilation on android was successful, but the textures are not loading correctly

demo videos

Desktop
https://www.youtube.com/watch?v=1vIpMaOleOU

Android
https://www.youtube.com/watch?v=UPzwgfyq_1o

What can it be ?

**Comment by SrJohnathan** [comment]
![Screenshot_20200626-114011](https://user-images.githubusercontent.com/22691849/85869937-c2435900-b7a2-11ea-8620-c291f53ebd11.png)

running on android :), but it doesn't load a texture, find out the problem in libgdx

**Comment by peed** [comment]
Awesome work! From what I can tell in the desktop one (which you may have
already fixed) is you need to work with the camera/viewport and make sure
variables like rotation, perspective, etc (there's A LOT of variables) are
all set correctly.

When it comes to android not loading textures is a common problem, this
might be due to the setup of the project, where the image files are stored
before/after build etc. See if you can run a simple "if exists" type script
to see if the resources are even recognized. They might have to be stored
specifically. A lot of this is off the top of my head from previous
experience, apologies if it's not much help.

**Comment by durswd** [comment]
It seem that the directory where textures exits is wrong or this() function has bugs

https://github.com/effekseer/EffekseerForMultiLanguages/blob/master/examples/libGdxSample/core/src/com/mygdx/game/libGdxSample.java#L92

**Comment by peed** [comment]
While I haven't worked with android in over a year, I definitely think
that's the issue, you may have to change the storage for android (load
everything into a jar and access it, possibly) as that function might only
work on desktop.

**Comment by SrJohnathan** [comment]
I am implementing a PNG file loader, it was missing on Android

the assets folder must be opened in NDK c ++ to load textures correctly

**Comment by SrJohnathan** [comment]
![Screenshot_2020-06-28-18-20-55](https://user-images.githubusercontent.com/22691849/85958555-ba371500-b96c-11ea-874a-8febc2e77b40.png)

![Screenshot_2020-06-28-18-29-13](https://user-images.githubusercontent.com/22691849/85958674-7abcf880-b96d-11ea-9a86-192caa8fa4b9.png)
![Screenshot_2020-06-28-18-34-10](https://user-images.githubusercontent.com/22691849/85958737-1484a580-b96e-11ea-9fe2-d69b05038d9d.png)


Perfect !!!!

PNG files are loading perfectly

 implement Models and Material

**Comment by durswd** [comment]
Great!

**Comment by durswd** [comment]
It's great!

> I am implementing a PNG file loader, it was missing on Android
Why... This flag is perhaps wrong...

https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/CMakeLists.txt#L19

**Comment by SrJohnathan** [comment]
> It's great!
> 
> > I am implementing a PNG file loader, it was missing on Android
> 
> Why... This flag is perhaps wrong...
> 
> https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/CMakeLists.txt#L19
> 
> It seems that it is easy to create a material loader by creating material loader directly
> https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.Renderer.cpp#L73

this flag is wrong

USE_INTERNAL_LOADER

compilation is being done with android.mk, not cmake

this flag of error the compilation

**Comment by SrJohnathan** [comment]
`include $(CLEAR_VARS)

LOCAL_PATH := $(call my-dir)



LOCAL_ARM_MODE  := arm
LOCAL_PATH      := $(NDK_PROJECT_PATH)
LOCAL_MODULE    := libEffekseer
LOCAL_CFLAGS    := -O2 -D__EFFEKSEER_RENDERER_GLES2__  -funwind-tables -Wl,--no-merge-exidx-entries 	
LOCAL_LDLIBS    := -llog -landroid -lEGL -lGLESv2 -ljnigraphics -lGLESv3 
APP_CPPFLAGS += -fexceptions



LOCAL_C_INCLUDES += \
	$(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/Effekseer \
	$(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/EffekseerRendererCommon \
	$(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/EffekseerRendererGL

LOCAL_SRC_FILES := \
	$(LOCAL_PATH)/particles_EffekseerCoreJNI.cpp \
	$(LOCAL_PATH)/lib/EffekseerSettingCore.cpp \
	$(LOCAL_PATH)/lib/EffekseerBackendCore.cpp \
	$(LOCAL_PATH)/lib/EffekseerEffectCore.cpp \
	$(LOCAL_PATH)/lib/EffekseerManagerCore.cpp \
	$(LOCAL_PATH)/lib/PngLouder.cpp \
	
	

LIB_SRC_PATH := $(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/Effekseer/Effekseer
LOCAL_SRC_FILES += \
	$(LIB_SRC_PATH)/Effekseer.Client.cpp \
	$(LIB_SRC_PATH)/Effekseer.Color.cpp \
	$(LIB_SRC_PATH)/Effekseer.DefaultEffectLoader.cpp \
	$(LIB_SRC_PATH)/Effekseer.DefaultFile.cpp \
	$(LIB_SRC_PATH)/Effekseer.Effect.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNode.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNodeModel.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNodeRibbon.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNodeRing.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNodeRoot.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNodeSprite.cpp \
	$(LIB_SRC_PATH)/Effekseer.EffectNodeTrack.cpp \
	$(LIB_SRC_PATH)/Effekseer.FCurves.cpp \
	$(LIB_SRC_PATH)/Effekseer.Instance.cpp \
	$(LIB_SRC_PATH)/Effekseer.InstanceContainer.cpp \
	$(LIB_SRC_PATH)/Effekseer.InstanceGlobal.cpp \
	$(LIB_SRC_PATH)/Effekseer.InstanceGroup.cpp \
	$(LIB_SRC_PATH)/Effekseer.InstanceChunk.cpp \
	$(LIB_SRC_PATH)/Effekseer.InternalScript.cpp \
	$(LIB_SRC_PATH)/Effekseer.Manager.cpp \
	$(LIB_SRC_PATH)/Effekseer.Matrix43.cpp \
	$(LIB_SRC_PATH)/Effekseer.Matrix44.cpp \
	$(LIB_SRC_PATH)/Effekseer.RectF.cpp \
	$(LIB_SRC_PATH)/Effekseer.Server.cpp \
	$(LIB_SRC_PATH)/Effekseer.Setting.cpp \
	$(LIB_SRC_PATH)/Effekseer.Socket.cpp \
	$(LIB_SRC_PATH)/Effekseer.Vector2D.cpp \
	$(LIB_SRC_PATH)/Effekseer.Vector3D.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.Grid.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.Layer.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.Matrix44.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.ObjectInternal.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.ReferenceObject.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.Vector3DF.cpp \
	$(LIB_SRC_PATH)/Culling/Culling3D.WorldInternal.cpp \
	$(LIB_SRC_PATH)/IO/Effekseer.EfkEfcFactory.cpp \
	$(LIB_SRC_PATH)/Material/Effekseer.CompiledMaterial.cpp \
	$(LIB_SRC_PATH)/Material/Effekseer.Material.cpp \
	$(LIB_SRC_PATH)/Material/Effekseer.MaterialCompiler.cpp \
	$(LIB_SRC_PATH)/Utils/Effekseer.CustomAllocator.cpp \
	$(LIB_SRC_PATH)/Parameter/Effekseer.Parameters.cpp \
	$(LIB_SRC_PATH)/SIMD/Effekseer.Mat43f.cpp \
	$(LIB_SRC_PATH)/SIMD/Effekseer.Mat44f.cpp \
	$(LIB_SRC_PATH)/SIMD/Effekseer.SIMDUtils.cpp

LIB_SRC_PATH := $(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/EffekseerMaterialCompiler
LOCAL_SRC_FILES += \
	$(LIB_SRC_PATH)/OpenGL/EffekseerMaterialCompilerGL.cpp

LIB_SRC_PATH := $(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/EffekseerRendererCommon
LOCAL_SRC_FILES += \
	$(LIB_SRC_PATH)/EffekseerRenderer.IndexBufferBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.ModelRendererBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.Renderer.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.Renderer_Impl.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.RenderStateBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.RibbonRendererBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.RingRendererBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.SpriteRendererBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.TrackRendererBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.VertexBufferBase.cpp \
	$(LIB_SRC_PATH)/EffekseerRenderer.CommonUtils.cpp

LIB_SRC_PATH := $(LOCAL_PATH)/../../../Effekseer/Dev/Cpp/EffekseerRendererGL/EffekseerRenderer
LOCAL_SRC_FILES += \
	$(LIB_SRC_PATH)/EffekseerRendererGL.DeviceObject.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.GLExtension.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.IndexBuffer.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.ModelLoader.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.ModelRenderer.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.MaterialLoader.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.Renderer.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.RenderState.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.Shader.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.TextureLoader.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.VertexArray.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.VertexBuffer.cpp \
	$(LIB_SRC_PATH)/EffekseerRendererGL.DeviceObjectCollection.cpp

include $(BUILD_SHARED_LIBRARY)`

**Comment by durswd** [comment]
I think that making __EFFEKSEER_RENDERER_INTERNAL_LOADER__ enabled and add files into android.mk is better.

**Comment by SrJohnathan** [comment]
> I think that making **EFFEKSEER_RENDERER_INTERNAL_LOADER** enabled and adding files into android.mk are better.


for use  **EFFEKSEER_RENDERER_INTERNAL_LOADER**, Effekseer scripts must be updated to use on android, using this flag, directx libraries are added and causes compilation error

**Comment by durswd** [comment]
oh... which file is included?

**Comment by durswd** [comment]
I updated Effekseer and Android.mk in EffekseerForUnity
It now can compile for Android with InternalFlag

https://github.com/effekseer/EffekseerForUnity/commit/9b377ae35c6ecdda56703d37138fef267e169444

**Comment by SrJohnathan** [comment]
Your build worked perfectly

in the libgdx render function

put like this

`Gdx.gl.glEnable(GL20.GL_BLEND);
        Gdx.gl.glClearColor(0f, 0f, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        Gdx.gl.glDepthMask(true);

//My creation function
        effekseerManagerCore.SetViewProjectionMatrixWithSimpleWindowPerspective(1280, 720);

        effekseerManagerCore.Update(Gdx.graphics.getDeltaTime() / (1.0f / 60.0f));
        effekseerManagerCore.DrawBack();
        effekseerManagerCore.DrawFront();


        Gdx.gl.glDisable(GL20.GL_BLEND);`

**Comment by durswd** [comment]
OK. It is no problem.
I wait your PR

**Comment by peed** [comment]
This is amazing work! So glad you got it working!!

**Comment by SrJohnathan** [comment]
![2020-06-30 13-27-21](https://user-images.githubusercontent.com/22691849/86152656-e66ea500-bad6-11ea-9047-8bfab049e7a5.gif)
![2020-06-30 13-31-42](https://user-images.githubusercontent.com/22691849/86152696-f4bcc100-bad6-11ea-8550-519621d1099d.gif)



projection error

when the camera moves

**Comment by durswd** [comment]
How do you calculate a projection matrix?

**Comment by SrJohnathan** [comment]
https://github.com/SrJohnathan/ParticlesNDK

https://github.com/SrJohnathan/ParticlesLIbgdx

**Comment by SrJohnathan** [comment]
There are the repositories with c ++ and libgdx, I need to organize the script

**Comment by SrJohnathan** [comment]
> ![2020-06-30 13-27-21](https://user-images.githubusercontent.com/22691849/86152656-e66ea500-bad6-11ea-9047-8bfab049e7a5.gif)
> ![2020-06-30 13-31-42](https://user-images.githubusercontent.com/22691849/86152696-f4bcc100-bad6-11ea-8550-519621d1099d.gif)
> 
> projection error
> 
> when the camera moves

I mapped the projection of the libgdx camera and sent it to Effekter,
soon the library will be ready for use

**Comment by SrJohnathan** [comment]
https://youtu.be/AY_3n0MHttM


3D finished

**Comment by durswd** [comment]
Amazing!

**Comment by SrJohnathan** [comment]
> Amazing!

https://github.com/SrJohnathan/ParticlesLIbgdx

https://github.com/SrJohnathan/LibGDXApplicationTest

https://github.com/SrJohnathan/ParticlesNDK


repositories

**Comment by durswd** [comment]
Would you clean up these codes?

**Comment by SrJohnathan** [comment]
> Would you clean up these codes?

You're talking about organizing the codes,
post comments or remove github repositories?

**Comment by durswd** [comment]
Excuse me.
I think that it is better to merge these codes into this repository.
But your repository has many unused and temp files and it difficult to understand where is fixed.

Whoever sends PR to this repository, it need to improve codes.

**Comment by SrJohnathan** [comment]
> Excuse me.
> I think that it is better to merge these codes into this repository.
> But your repository has many unused and temp files and it difficult to understand where is fixed.
> 
> Whoever sends PR to this repository, it need to improve codes.


ok, i will clone your project again and put the new code, but it would be good to make a new repository and separate libgdx from C #

**Comment by durswd** [comment]
Thank you

**Comment by SrJohnathan** [comment]
> Thank you


intending to publish in the maven repository, to facilitate the use in libgdx and gradle, for consumers, is there a problem with me doing this?

**Comment by durswd** [comment]
no problem.

**Comment by SrJohnathan** [comment]
there is some callback in the responsible c ++ API after ending the animation, i need to implement an OnAnimationComplete in java

**Comment by durswd** [comment]
It is better to create callback class with swig

**Comment by SrJohnathan** [comment]
> It is better to create callback class with swig


Sorry, I don't use SWIG, I don't know how it works, I'm reading the documentation to know about SWIG, I do everything without a wrapper :)

**Comment by durswd** [comment]
OK. I understood that it cannot merge this repository.

**Comment by SrJohnathan** [comment]
https://github.com/SrJohnathan/ParticlesLIbgdx
