### ISSUE TITLE
Distortion doesnt work

### ISSUE THREAD

**Issue by TwentyBytes** [effekseer/EffekseerForMultiLanguages#31]
Hello. For some reason Distortion function doesn't work, I understand it's because of lack of FrameBuffer support. Can you fix it? This effect greatly affects the gameplay experience and visuals of the game and partials. I really ask you to do it if possible 

I am using this library Java (Minecraft)

**Comment by durswd** [comment]
Please call SetBackground

**Comment by TwentyBytes** [comment]
do I understand correctly that in this method you need to pass the texture id, which is the rendered frame of the game? Please explain how I can use this function and what needs to be passed to it in order for it to work correctly. Thank you in advance for your help

**Comment by TwentyBytes** [comment]
Hi, i fixed it. Thx for ur help.

How i do it:
I just send game FrameBuffer GL textureId in method SetBackground after game render finished, and after i call draw effect and after call UnsetBackground.
